### PR TITLE
Issue resolved

### PR DESCRIPTION
**Pull request by raj-bunsha**
This makes the problem of different color introduced with the update solved

### CODE REVIEW

**Comment by RudreshVeerkhare** [comment]
Thanks for the PR I'll review and Merge it a day or two.. and sorry for the delay caused.

**Comment by tausiq** [comment]
Hi @RudreshVeerkhare Can you please review the PR and if all is okay, publish an update to the marketplace?

**Comment by RudreshVeerkhare** [comment]
@raj-bunsha thanks for the PR, I'll review and check it once...

**Comment by RudreshVeerkhare** [comment]
@raj-bunsha thanks for the PR, but I found another way to solve the issue without a need for writing custom regex to remove divs, fixed in version `1.7.12`. But any further contributions are always welcome.

**Pull request closed without merging**
